name: Kernel build

on:
  # run daily at 00:00
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  NUM_JOBS: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: bcm2835
            arch: arm
            defconfig: bcm2835_defconfig
            kernel: kernel

          - name: arm64
            arch: arm64
            defconfig: defconfig
            kernel: kernel8

          - name: bcmrpi
            arch: arm
            defconfig: bcmrpi_defconfig
            kernel: kernel

          - name: bcm2709
            arch: arm
            defconfig: bcm2709_defconfig
            kernel: kernel7

          - name: bcm2711
            arch: arm
            defconfig: bcm2711_defconfig
            kernel: kernel7l

          - name: bcm2711_arm64
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8

          - name: bcm2712
            arch: arm64
            defconfig: bcm2712_defconfig
            kernel: kernel_2712

    steps:
    - name: Update install
      run:
        sudo apt-get update

    - name: Install toolchain
      run:
        if [[ "${{matrix.arch}}" == "arm64" ]]; then
          sudo apt-get install gcc-aarch64-linux-gnu;
        else
          sudo apt-get install gcc-arm-linux-gnueabihf;
        fi
      timeout-minutes: 5

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        clean: true

    - name: Clone rpi linux kernel source
      run: git clone --depth=1 https://github.com/raspberrypi/linux ./rpi-linux

    - name: Build kernel ${{matrix.name}}
      run: |
        mkdir ${{github.workspace}}/rpi-linux/build
        export ARCH=${{matrix.arch}}
        if [[ "$ARCH" == "arm64" ]]; then
          export CROSS_COMPILE=aarch64-linux-gnu-
          export DTS_SUBDIR=broadcom
          export IMAGE=Image.gz
        else
          export CROSS_COMPILE=arm-linux-gnueabihf-
          export DTS_SUBDIR=
          export IMAGE=zImage
        fi
        make O=${{github.workspace}}/rpi-linux/build ${{matrix.defconfig}}
        scripts/config --file ${{github.workspace}}/rpi-linux/build/.config --set-val CONFIG_WERROR y
        # enable serpent crypto support
        scripts/config --file ${{github.workspace}}/rpi-linux/build/.config --set-val CONFIG_CRYPTO_SERPENT y
        make O=${{github.workspace}}/rpi-linux/build -j ${{env.NUM_JOBS}} $IMAGE modules dtbs
        mkdir -p ${{github.workspace}}/rpi-linux/install/boot/overlays
        make O=${{github.workspace}}/rpi-linux/build INSTALL_MOD_PATH=${{github.workspace}}/rpi-linux/install modules_install
        cp ${{github.workspace}}/rpi-linux/build/arch/${ARCH}/boot/dts/${DTS_SUBDIR}/*.dtb ${{github.workspace}}/rpi-linux/install/boot/
        cp ${{github.workspace}}/rpi-linux/build/arch/${ARCH}/boot/dts/overlays/*.dtb* ${{github.workspace}}/rpi-linux/install/boot/overlays/
        cp ${{github.workspace}}/rpi-linux/arch/${ARCH}/boot/dts/overlays/README ${{github.workspace}}/rpi-linux/install/boot/overlays/
        cp ${{github.workspace}}/rpi-linux/build/arch/${ARCH}/boot/$IMAGE ${{github.workspace}}/rpi-linux/install/boot/${{matrix.kernel}}.img

    - name: Tar build
      run: tar -cvf ${{matrix.name}}_build.tar -C ${{github.workspace}}/rpi-linux/install .

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}_build
        path: ${{matrix.name}}_build.tar
        retention-days: 90
